# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/guard-shell/all/guard-shell.rbi
#
# guard-shell-0.7.1

module Guard
end
module Guard::ShellVersion
end
class Guard::Shell < Guard::Plugin
  def run_all; end
  def run_on_modifications(res); end
  def start; end
  def stop; end
end
class Guard::Dsl
  def eager(command); end
  def n(msg, title = nil, image = nil); end
end
